<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041)
 -->
<!-- Title: tpy::PyFetchedException Pages: 1 -->
<svg width="135pt" height="82pt"
 viewBox="0.00 0.00 134.62 82.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 78)">
<title>tpy::PyFetchedException</title>
<!-- Node2 -->
<g id="node1" class="node"><title>Node2</title>
<polygon fill="#bfbfbf" stroke="black" points="0,-0.5 0,-18.5 126.615,-18.5 126.615,-0.5 0,-0.5"/>
<text text-anchor="middle" x="63.3076" y="-6.5" font-family="Helvetica,sans-Serif" font-size="10.00">tpy::PyFetchedException</text>
</g>
<!-- Node3 -->
<g id="node2" class="node"><title>Node3</title>
<g id="a_node2"><a doxygen="/Users/philippe/Research/projects/tomographer/doc/cppreference-doxygen-web.tag.xml:http://en.cppreference.com/w/" xlink:href="http://en.cppreference.com/w/cpp/error/exception.html" target="_top" xlink:title="STL class. ">
<polygon fill="none" stroke="black" points="24.4556,-55.5 24.4556,-73.5 102.16,-73.5 102.16,-55.5 24.4556,-55.5"/>
<text text-anchor="middle" x="63.3076" y="-61.5" font-family="Helvetica,sans-Serif" font-size="10.00">std::exception</text>
</a>
</g>
</g>
<!-- Node3&#45;&gt;Node2 -->
<g id="edge1" class="edge"><title>Node3&#45;&gt;Node2</title>
<path fill="none" stroke="midnightblue" d="M63.3076,-45.1746C63.3076,-36.0945 63.3076,-25.5949 63.3076,-18.5496"/>
<polygon fill="midnightblue" stroke="midnightblue" points="59.8077,-45.2187 63.3076,-55.2188 66.8077,-45.2188 59.8077,-45.2187"/>
</g>
</g>
</svg>
